# Generated by Django 5.1.1 on 2024-09-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
    ]
