# Generated by Django 5.1.1 on 2024-09-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0003_rename_full_name_student_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
