# Generated by Django 5.1.1 on 2024-09-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0004_rename_subject_name_subject_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
